NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.LSH8-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.LSH8-cert.pem
    OrganizationalUnitIdentifier: peer
