NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.LSH5-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.LSH5-cert.pem
    OrganizationalUnitIdentifier: peer
